title: SIOMAI - PRODAMAI Kota Magelang
email: layanan.prodamai@gmail.com
description: >-
  Sistem Informasi Program Pemberdayaan Masyarakat (PRODAMAI) 
  – Monitoring dan Evaluasi Program Pemberdayaan di Kota Magelang.
baseurl: "/siomai"  # kosong jika domain root, atau "/siomai-blog" jika di subfolder ges
url: "https://fasilitatormgl.github.io"  # ganti dengan URL GitHub Anda
author: Fasilitator PRODAMAI

# Build settings
markdown: kramdown
permalink: /artikel/:year/:month/:day/:title/
plugins:
  - jekyll-feed

# Default front matter untuk halaman
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
