backend:
  name: github
  repo: fasilitatormgl/siomai
  branch: main

# Pengaturan folder gambar (dibuat relatif tanpa tanda miring di awal)
media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

# Pengaturan Form Penulisan Artikel
collections:
  - name: "artikel"
    label: "Artikel / Berita"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Kategori", name: "categories", widget: "string" }
      - { label: "Gambar Cover / Utama", name: "image", widget: "image", required: false }
      - { label: "Konten / Isi Berita", name: "body", widget: "markdown" }
