name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main # Ubah ke 'master' jika branch utama Anda namanya master

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🕵️ SKRIP DETEKTIF: Mengecek apakah rahasia terbaca atau kosong
      - name: Cek Status Kunci Rahasia
        run: |
          if [ -z "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" ]; then
            echo "❌ GAGAL: KUNCI RAHASIA KOSONG / TIDAK TERBACA OLEH GITHUB!"
            exit 1
          else
            echo "✅ SUKSES: Kunci rahasia berhasil ditemukan!"
          fi

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Fix Platform & Install Dependencies
        run: |
          bundle lock --add-platform x86_64-linux
          bundle install

      - name: Build Website
        run: bundle exec jekyll build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: siomaimagelang
          channelId: live
